export const supermarches = [
  {
    nom: 'Park Slop<br>Food Coop',
    adresse: '782 Union Street, Brooklyn',
    ville: 'New York',
    departement: '',
    pays: 'USA',
    logo: 'food_coop.png',
    site_web: 'https://www.foodcoop.com/',
    avancement: 5,
    latitude: 40.67473,
    longitude: -73.97682
  },
  {
    nom: 'Nice Coop',
    adresse: '42 rue Vernier',
    ville: 'Nice',
    departement: '06',
    pays: 'France',
    logo: 'logo-NC.png',
    site_web: 'http://nicecoop.fr/',
    courriel: 'nicecoop06@gmail.com',
    facebook: 'https://www.facebook.com/nicecoop2/',
    avancement: 4,
    latitude: 43.70701,
    longitude: 7.25735
  },
  {
    nom: 'Coop La Meute',
    adresse: '59 avenue de la libération',
    ville: 'Grasse',
    departement: '06',
    pays: 'France',
    logo: 'la_meute.jpg',
    site_web: 'https://www.cooplameute.fr/',
    courriel: 'contact@cooplameute.fr',
    facebook: 'https://www.facebook.com/cooplameute/',
    avancement: 4,
    latitude: 43.64652,
    longitude: 6.91408
  },
  {
    nom: 'Marcasserie',
    adresse: '7 place de Montcy Saint Pierre',
    ville: 'Charleville-Mézières',
    departement: '08',
    pays: 'France',
    logo: 'marcasserie.jpg',
    site_web: 'http://marcasserie.org/',
    courriel: 'contact@marcasserie.org',
    facebook: 'https://www.facebook.com/marcasserie/',
    avancement: 4,
    latitude: 49.77742,
    longitude: 4.73542
  },
  {
    nom: 'Super Cafoutch',
    adresse: '16 rue du Chevalier Roze',
    ville: 'Marseille 2è arr.',
    departement: '13',
    pays: 'France',
    logo: 'super_cafoutch.png',
    site_web: 'https://supercafoutch.fr/',
    courriel: 'contact@supercafoutch.fr',
    facebook: 'https://www.facebook.com/supercafoutch/',
    avancement: 5,
    latitude: 43.29856,
    longitude: 5.37166
  },
  {
    nom: "Aix'Elan Coop",
    adresse: '',
    ville: 'Aix-en-Provence',
    departement: '13',
    pays: 'France',
    logo: 'aixelan_nouveau.png',
    site_web: 'http://www.aixelancoop.fr/',
    courriel: 'contact.aixelancoop@gmail.com',
    facebook: 'https://www.facebook.com/AixElanCoop/',
    avancement: 1,
    latitude: 43.5575,
    longitude: 5.4890
  },
  {
    nom: 'La Roch’coop',
    adresse: '9 place du général de Gaulle',
    ville: 'Puilboreau, La Rochelle',
    departement: '17',
    pays: 'France',
    logo: 'roch-coop.png',
    site_web: 'https://larochcoop.fr/',
    courriel: 'contact@larochcoop.fr',
    facebook: 'https://www.facebook.com/LaRochcoop',
    avancement: 5,
    latitude: 46.186031,
    longitude: -1.117599
  },
  {
    nom: 'Court circuit 21',
    adresse: '23, rue de la justice',
    ville: 'Chenove',
    departement: '21',
    pays: 'France',
    logo: 'court-circuit_new.png',
    site_web: 'https://www.courtcircuit21.org/',
    courriel: 'contact@courtcircuit21.org',
    facebook: 'https://www.facebook.com/courtcircuit21/',
    avancement: 4,
    latitude: 47.29516,
    longitude: 5.02020
  },
  {
    nom: 'La briochaine',
    adresse: undefined,
    ville: 'Saint-Brieuc',
    departement: '22',
    pays: 'France',
    logo: 'labriochaine.png',
    courriel: 'bienvenue@labriochaine.fr',
    facebook: 'https://www.facebook.com/labriochaine/',
    avancement: 1,
    latitude: 48.49867,
    longitude: -2.74692
  },
  {
    nom: "T'as meilleur temps !",
    adresse: '31 Boulevard Kennedy',
    ville: 'Besançon',
    departement: '25',
    pays: 'France',
    logo: 'creacoop25.jpg',
    site_web: 'http://www.tas-meilleur-temps.fr/',
    courriel: 'magasin@tasmeilleurtemps.fr',
    facebook: 'https://www.facebook.com/creacoop25/',
    avancement: 4,
    latitude: 47.2350,
    longitude: 5.9852
  },
  {
    nom: 'La Carline',
    adresse: '21, Rue Du Viaduc',
    ville: 'Die',
    departement: '26',
    pays: 'France',
    logo: 'carline.png',
    site_web: 'https://www.lacarline.coop/',
    courriel: 'epicerie@lacarline.coop',
    facebook: 'https://www.facebook.com/LaCarlineCoop/',
    avancement: 4,
    latitude: 44.75223,
    longitude: 5.37471
  },
  {
    nom: 'Ti Coop',
    adresse: '209 rue Jean Jaurès',
    ville: 'Brest',
    departement: '29',
    pays: 'France',
    logo: 'ti_coop.jpg',
    site_web: 'https://ticoop.fr/',
    courriel: 'contact@ticoop.fr',
    facebook: 'https://www.facebook.com/TiCoopBrest',
    avancement: 4,
    latitude: 48.39912,
    longitude: -4.47222
  },
  {
    nom: 'Le Gase de la Baie',
    adresse: 'Chapelle St Joseph<br>13 rue Villeneuve<br>29600 Morlaix',
    ville: 'Morlaix',
    departement: '29',
    pays: 'France',
    logo: 'gasieresdelabaie.webp',
    site_web: 'https://gasieresdelabaie.wordpress.com/',
    courriel: 'lesgasieresdelabaie@gmail.com',
    facebook: 'https://www.facebook.com/Supermarch%C3%A9-Coop%C3%A9ratif-Morlaix-103110237852247/',
    avancement: 3,
    latitude: 48.58208,
    longitude: -3.83405
  },
  {
    nom: 'La RieCoop',
    adresse: '25 rue François Cadoret<br>29340 Riec-sur-Bélon',
    ville: 'Riec-sur-Bélon',
    departement: '29',
    pays: 'France',
    logo: 'lariecoop.png',
    site_web: 'https://lariecoop.wixsite.com/epicerie',
    courriel: 'lariecoop@gmail.com',
    facebook: 'https://www.facebook.com/laRIECoop/',
    avancement: 4,
    latitude: 47.84409,
    longitude: -3.69194
  },
  {
    nom: 'La chouette coop',
    adresse: '5 rue René Leduc',
    ville: 'Toulouse',
    departement: '31',
    pays: 'France',
    logo: 'La_Chouette.png',
    site_web: 'https://lachouettecoop.fr/',
    courriel: 'contact@lachouettecoop.fr',
    facebook: 'https://www.facebook.com/lachouettecoop/',
    avancement: 4,
    latitude: 43.61127,
    longitude: 1.45657
  },
  {
    nom: 'SuperCoop',
    adresse: '19 rue Oscar et Jean Auriac',
    ville: 'Bordeaux',
    departement: '33',
    pays: 'France',
    logo: 'supercoop.jpg',
    site_web: 'https://supercoop.fr/',
    courriel: 'contact@supercoop.fr',
    facebook: 'https://www.facebook.com/supercoopbdx/',
    avancement: 5,
    latitude: 44.81460,
    longitude: -0.55419
  },
  {
    nom: 'CoopOcéan',
    adresse: '',
    ville: 'Soulac-sur-Mer',
    departement: '33',
    pays: 'France',
    logo: 'coopocean.jpg',
    facebook: 'https://www.facebook.com/groups/1035375806594111/',
    avancement: 1,
    latitude: 45.5070,
    longitude: -1.1197
  },
  {
    nom: 'La Coopé',
    adresse: '3 chemin de la garenne<br>33210 Langon',
    ville: 'Langon',
    departement: '33',
    pays: 'France',
    logo: 'langon_les_amis_de_la_coope.png',
    site_web: 'https://lacoope.fr/',
    courriel: 'lesamis@lacoope.fr',
    facebook: 'https://www.facebook.com/lacoopelangon/',
    avancement: 4,
    latitude: 44.5474,
    longitude: -0.2490
  },
  {
    nom: 'La cagette',
    adresse: '19 avenue Clémenceau',
    ville: 'Montpellier',
    departement: '34',
    pays: 'France',
    logo: 'cagette.jpg',
    site_web: 'https://lacagette-coop.fr/',
    courriel: 'contact@lacagette-coop.fr',
    bluesky: 'https://bsky.app/profile/lacagette34.bsky.social',
    instagram: 'https://www.instagram.com/lacagette34/',
    facebook: 'https://www.facebook.com/LaCagette34',
    linkedin: 'https://www.linkedin.com/company/la-cagette-de-montpellier',
    mastodon: 'https://piaille.fr/%40lacagette34',
    peertube: 'https://indymotion.fr/c/la_cagette/videos',
    // twitter: 'https://twitter.com/LaCagetteMtp34',
    // youtube: 'https://www.youtube.com/channel/UCWaWBUP1OQukUew8MWCDymQ',
    avancement: 5,
    latitude: 43.60398,
    longitude: 3.87330
  },
  {
    nom: 'La Crèmerie',
    adresse: '128 Rue du Romarin<br>34830 Clapiers',
    ville: 'Clapiers',
    departement: '34',
    pays: 'France',
    logo: 'la_cremerie.png',
    site_web: 'http://www.lacremerie-coop.fr/',
    courriel: 'contact@lacremerie-coop.fr',
    facebook: 'https://www.facebook.com/LaCremerieCoopClapiers',
    avancement: 4,
    latitude: 43.6576,
    longitude: 3.8837
  },
  {
    nom: 'Coop singulière',
    adresse: '38 rue Pierre Sémard',
    ville: 'Sète',
    departement: '34',
    pays: 'France',
    logo: 'coop_singuliere.png',
    site_web: 'https://coopsinguliere.fr/',
    courriel: 'contact@coopsinguliere.fr',
    facebook: 'https://www.facebook.com/CoopSinguliere/',
    avancement: 4,
    latitude: 43.40554,
    longitude: 3.69974
  },
  {
    nom: 'Breizhicoop',
    adresse: '15 Avenue de Pologne',
    ville: 'Rennes',
    departement: '35',
    pays: 'France',
    logo: 'breizhicoop.jpg',
    site_web: 'https://www.breizhicoop.fr/',
    courriel: 'contact@breizhicoop.fr',
    facebook: 'https://www.facebook.com/breizhicoop/',
    avancement: 4,
    latitude: 48.08464,
    longitude: -1.65050
  },
  {
    nom: 'Le Troglo',
    adresse: '15 boulevard Louis XI',
    ville: 'Tours',
    departement: '37',
    pays: 'France',
    logo: 'letroglo.jpg',
    site_web: 'https://www.le-troglo.fr/',
    courriel: 'bureau.coops@le-troglo.fr',
    facebook: 'https://www.facebook.com/LeTroglo/',
    avancement: 5,
    latitude: 47.37551,
    longitude: 0.671992
  },
  {
    nom: 'L’éléfàn',
    adresse: '30 bis Avenue Marcelin Berthelot',
    ville: 'Grenoble',
    departement: '38',
    pays: 'France',
    logo: 'Lelefan.png',
    site_web: 'https://lelefan.org',
    courriel: 'contact@lelefan.org',
    facebook: 'https://www.facebook.com/lelefandegrenoble/',
    avancement: 4,
    latitude: 45.1750672,
    longitude: 5.7304083
  },
  {
    nom: 'Les ami.e.s de Coop\'cinelles',
    adresse: '28 chemin des couloures<br>38300 Bourgoin Jallieu',
    ville: 'Bourgoin Jallieu',
    departement: '38',
    pays: 'France',
    logo: 'coop-cinelles.jpg',
    site_web: 'https://les-amies-de-coopcinelles.pepsup.com/',
    courriel: 'coopcinelles38@gmail.com',
    facebook: 'https://www.facebook.com/lesami.e.sdecoopcinelles/',
    avancement: 4,
    latitude: 45.6130,
    longitude: 5.2782
  },
  {
    nom: 'La Marm"Hotte',
    adresse: '55 Grande Rue<br>38530 Barraux',
    ville: 'Barraux',
    departement: '38',
    pays: 'France',
    logo: 'la_marm_hotte.jpg',
    site_web: 'https://la-marmhotte.org/',
    courriel: 'contact@la-marmhotte.org',
    facebook: 'https://www.facebook.com/lamarmhotte/',
    avancement: 4,
    latitude: 45.4339,
    longitude: 5.9769
  },
  {
    nom: 'La Cambuse',
    adresse: '69, rue du Pont Neuf<br>39000 Lons le Saunier',
    ville: 'Lons le Saunier',
    departement: '39',
    pays: 'France',
    logo: 'La_Cambuse.jpg',
    courriel: 'contact@cooplacambuse.fr',
    facebook: 'https://www.facebook.com/magasincooperatitflonslesaunier/',
    avancement: 4,
    latitude: 46.67450,
    longitude: 5.54819
  },
  {
    nom: 'La Fourmilière',
    adresse: '19 rue Nicolas Chaize',
    ville: 'Saint-Etienne',
    departement: '42',
    pays: 'France',
    logo: 'fourmiliere.jpg',
    site_web: 'http://coop-lafourmiliere.fr/',
    courriel: 'contact@coop-lafourmiliere.fr',
    avancement: 5,
    latitude: 45.41849,
    longitude: 4.39713
  },
  {
    nom: 'La libellule',
    adresse: '8 avenue de la Libération<br>Le Coteau 42120',
    ville: 'Le coteau',
    departement: '42',
    pays: 'France',
    logo: 'la_libellule_42.jpg',
    site_web: 'https://epicerielalibellule.wordpress.com/',
    courriel: 'lalibellule.contact@framalistes.org',
    facebook: 'https://www.facebook.com/lalibellule42',
    avancement: 4,
    latitude: 46.0313,
    longitude: 4.0824
  },
  {
    nom: 'Scopéli',
    adresse: '20 Rue de l’Abbé Grégoire,<br> 44 400 Rezé',
    ville: 'Nantes',
    departement: '44',
    pays: 'France',
    logo: 'scopeli.png',
    site_web: 'http://www.scopeli.fr/',
    courriel: 'contact@scopeli.fr',
    facebook: 'https://www.facebook.com/Scopeli/',
    avancement: 5,
    latitude: 47.19546,
    longitude: -1.56828
  },
  {
    nom: 'La Coop du Coin',
    adresse: '35 Boulevard Léon Gambetta',
    ville: 'Saint-Nazaire',
    departement: '44',
    pays: 'France',
    logo: 'coop-du-Coin.png',
    site_web: 'https://lacoopducoin-epicerie-cooperative-participative.fr/',
    courriel: 'lesamisdelacoopducoin@gmail.com',
    facebook: 'https://www.facebook.com/lesamisdelacoopducoin/',
    avancement: 4,
    latitude: 47.27771,
    longitude: -2.21737
  },
  {
    nom: 'La coopérette',
    adresse: '10 avenue francois rabelais<br>Saint Jean de Braye – 45800',
    ville: 'Orléans',
    departement: '45',
    pays: 'France',
    logo: 'cooperette.jpg',
    site_web: 'https://lacooperette.fr/',
    courriel: 'contact@lacooperette.fr',
    facebook: 'https://www.facebook.com/supermarchecooperatiforleans',
    avancement: 3,
    latitude: 47.90714,
    longitude: 1.95224
  },
  {
    nom: 'La Gabare',
    adresse: '1455 Rue de la Bergeresse<br>Olivet - 45160',
    ville: 'Orléans',
    departement: '45',
    pays: 'France',
    logo: 'la_gabare.png',
    site_web: 'https://www.la-gabare-orleans.coop/',
    courriel: 'hello@la-gabare-orleans.coop',
    facebook: 'https://www.facebook.com/LaGabare45/',
    avancement: 5,
    latitude: 47.84593,
    longitude: 1.91945
  },
  {
    nom: "La coop'agenoise",
    adresse: '',
    ville: 'Agen',
    departement: '47',
    pays: 'France',
    logo: 'coop_agenaise.jpg',
    courriel: 'supermarchecoopagen@bbox.fr',
    facebook: 'https://www.facebook.com/LaCoopAgenaise/',
    avancement: 1,
    latitude: 44.2046512,
    longitude: 0.622364
  },
  {
    nom: 'Ma Coop <br>La Vie au Vert',
    adresse: 'Place Edouard Fournier',
    ville: 'Pied-de-Borne',
    departement: '48',
    pays: 'France',
    logo: 'lavieauvert.jpg',
    site_web: 'http://cdurable.info/-Ma-Coop-La-Vie-au-Vert-75-',
    courriel: 'macoop@cdurable.info',
    facebook: 'https://www.facebook.com/MaCoopLaVieAuVert/',
    avancement: 4,
    latitude: 44.47569,
    longitude: 3.98530
  },
  {
    nom: 'La Coopette',
    adresse: undefined,
    ville: 'Angers',
    departement: '49',
    pays: 'France',
    logo: 'lacoopette.png',
    courriel: 'coopette@netc.fr',
    facebook: 'https://www.facebook.com/coopette.angers/',
    avancement: 3,
    latitude: 47.47185,
    longitude: -0.54760
  },
  {
    nom: 'coop en Baie',
    adresse: '',
    ville: 'Avranches/Granville',
    departement: '50',
    pays: 'France',
    logo: 'coopenbaie.png',
    site_web: 'http://coopenbaie.fr/',
    facebook: 'https://www.facebook.com/coopenbaie/',
    avancement: 1,
    latitude: 48.8418002,
    longitude: -1.5822933
  },
  {
    nom: 'Grande épicerie générale',
    adresse: '88 avenue du XX corps',
    ville: 'Nancy',
    departement: '54',
    pays: 'France',
    logo: 'grande_epicerie.jpg',
    site_web: 'https://www.grandeepiceriegenerale.fr/',
    courriel: 'contact@grandeepiceriegenerale.fr',
    facebook: 'https://www.facebook.com/GEGNancy/',
    avancement: 4,
    latitude: 48.69811,
    longitude: 6.20029
  },
  {
    nom: 'Coop des Vénètes',
    adresse: '3 Rue de Lorraine<br>56860 Séné',
    ville: 'Séné',
    departement: '56',
    pays: 'France',
    logo: 'coop_venetes.jpg',
    site_web: 'https://www.coopdesvenetes.bzh/',
    courriel: 'contact@coopdesvenetes.bzh',
    facebook: 'https://www.facebook.com/coopdesvenetes/',
    avancement: 4,
    latitude: 47.65080,
    longitude: -2.71331
  },
  {
    nom: 'Graoucoop',
    adresse: '11 Rue du XXe corps',
    ville: 'Metz',
    departement: '57',
    pays: 'France',
    logo: 'logo-graoucoop.png',
    site_web: 'https://graoucoop.fr/',
    courriel: 'info@graoucoop.fr',
    facebook: 'https://www.facebook.com/graoucoop',
    avancement: 4,
    latitude: 49.103996,
    longitude: 6.165329
  },
  {
    nom: 'La Cocotte',
    adresse: undefined,
    ville: 'Nevers',
    departement: '58',
    pays: 'France',
    logo: 'la_cocotte.jpg',
    courriel: 'cooperativenevers@riseup.net',
    facebook: 'https://www.facebook.com/lacocottemagasincooperatifnevers',
    avancement: 3,
    latitude: 46.98903,
    longitude: 3.16134
  },
  {
    nom: 'SuperQuinquin',
    adresse: '55 rue Pierre Legrand',
    ville: 'Lille',
    departement: '59',
    pays: 'France',
    logo: 'superquinquin.png',
    site_web: 'https://superquinquin.fr/',
    courriel: 'jarrive@superquinquin.fr',
    facebook: 'https://www.facebook.com/SuperQuinquin-1060478380629115/',
    avancement: 5,
    latitude: 50.63228,
    longitude: 3.08717
  },
  {
    nom: 'La Baraque En Vrac',
    adresse: '44 Rue Jeanne Maillotte<br>59110 La Madeleine',
    ville: 'La Madeleine',
    departement: '59',
    pays: 'France',
    logo: 'la_baraque_en_vrac.png',
    site_web: 'https://labaraqueenvrac.com/',
    courriel: 'labaraque.vrac@gmail.com',
    facebook: 'https://www.facebook.com/labaraque.envrac/',
    avancement: 2,
    latitude: 50.65143,
    longitude: 3.06997
  },
  {
    nom: 'La Clac',
    adresse: '4 allée de la faïencerie',
    ville: 'Creil',
    departement: '60',
    pays: 'France',
    logo: 'clac.png',
    courriel: 'asso.creonslacoop@gmail.com',
    facebook: 'https://www.facebook.com/Creonslacoop/',
    avancement: 4,
    latitude: 49.2561,
    longitude: 2.4658
  },
  {
    nom: 'La coop des dômes',
    adresse: '103 rue d’Aulteribe',
    ville: 'Clermont-Ferrand',
    departement: '63',
    pays: 'France',
    logo: 'LaCoopDesDomes.jpg',
    site_web: 'http://www.coopdesdomes.fr/',
    courriel: 'contact@coopdesdomes.fr',
    facebook: 'https://www.facebook.com/CoopDesDomes',
    avancement: 4,
    latitude: 45.81259,
    longitude: 3.12860
  },
  {
    nom: "L'alternateur'",
    adresse: '17-19 Rue du Monastère',
    ville: 'SAUXILLANGES',
    departement: '63',
    pays: 'France',
    logo: 'alternateur.jpg',
    site_web: 'http://www.alternateur63.fr/',
    facebook: 'https://www.facebook.com/alternateursauxillanges/',
    avancement: 4,
    latitude: 45.55090,
    longitude: 3.37189
  },
  {
    nom: 'Otsokop',
    adresse: '1, avenue de Lattre de Tassigny',
    ville: 'Bayonne',
    departement: '64',
    pays: 'France',
    logo: 'OTSOKOP.PNG',
    site_web: 'http://www.otsokop.org/',
    courriel: 'contact@otsokop.org',
    facebook: 'https://www.facebook.com/otsokop/',
    avancement: 4,
    latitude: 43.502204,
    longitude: -1.4705459
  },
  {
    nom: 'Larrunkoop Urrugne',
    adresse: 'Go Etche<br>3 Rue Dongaitz Anaiak<br>64122 Urrugne',
    ville: 'Urrugne',
    departement: '64',
    pays: 'France',
    logo: 'Larrunkoop.jpg',
    courriel: 'larrunkoop@gmail.com',
    facebook: 'https://www.facebook.com/larrunkoop/',
    avancement: 4,
    latitude: 43.36436,
    longitude: -1.69864
  },
  {
    nom: 'Hendaia Koop',
    adresse: '10 rue du Port <br> 64700 Hendaye',
    ville: 'Hendaye',
    departement: '64',
    pays: 'France',
    logo: 'hendaiakoop.png',
    site_web: 'https://hendaiakoop.org',
    courriel: 'hendaiakoop@gmail.com',
    facebook: 'https://www.facebook.com/hendaiakoop/',
    avancement: 4,
    latitude: 43.35817,
    longitude: -1.77568
  },
  {
    nom: 'Coop des Luys',
    adresse: '3 place du champ de foire',
    ville: 'Sauvagnon',
    departement: '64',
    pays: 'France',
    logo: 'coop-luys.jpg',
    site_web: 'https://coopdesluys.fr/',
    courriel: 'contact.coopdesluys@gmail.com',
    avancement: 4,
    latitude: 43.404078,
    longitude: -0.38633
  },
  {
    nom: 'O Vrac Coop',
    adresse: '145 Chemin de la  Passio Vella<br>66100 Perpignan',
    ville: 'Perpignan',
    departement: '66',
    pays: 'France',
    logo: 'ovracoop.jpg',
    site_web: 'http://ovrac-coop.fr/',
    courriel: 'o.vrac.coop66@gmail.com',
    facebook: 'https://www.facebook.com/ovrac.coop/',
    avancement: 4,
    latitude: 42.67770,
    longitude: 2.89405
  },
  {
    nom: 'Coopalim',
    adresse: '7 rue Kageneck',
    ville: 'Strabourg',
    departement: '67',
    pays: 'France',
    logo: 'coopalim.png',
    site_web: 'https://coopalimstrasbourg.com/',
    courriel: 'coopalim@gmail.com',
    facebook: 'https://www.facebook.com/coopalim.strasbourg/',
    avancement: 4,
    latitude: 48.58412,
    longitude: 7.73854
  },
  {
    nom: 'Les Oies Sauvages',
    adresse: '27 rue du Logelbach',
    ville: 'Colmar',
    departement: '68',
    pays: 'France',
    logo: 'oies_sauvages.png',
    site_web: 'https://cooplesoiessauvages.alsace/',
    courriel: 'contact@CoopLesOiesSauvages.Alsace',
    facebook: 'https://www.facebook.com/CoopLesOiesSauvages/',
    avancement: 4,
    latitude: 48.08105,
    longitude: 7.34906
  },
  {
    nom: 'Le Panier du Mehlala',
    adresse: '52 avenue Aristide Briand',
    ville: 'Mulhouse',
    departement: '68',
    pays: 'France',
    logo: 'mehlala.jpg',
    site_web: 'https://mehlala.net/',
    courriel: 'contact@mehlala.net',
    facebook: 'https://www.facebook.com/epicerieparticipativemulhouse/',
    avancement: 4,
    latitude: 47.74908,
    longitude: 7.32568
  },
  {
    nom: 'La Melting Coop<br>(Anciennement Demain)',
    adresse: '229 cours Émile Zola',
    ville: 'Villeurbanne',
    departement: '69',
    pays: 'France',
    logo: 'lameltingcoop.jpg',
    site_web: 'http://www.demainsupermarche.org/',
    courriel: 'communicationdemain@gmail.com',
    facebook: 'https://www.facebook.com/Lameltingcoop',
    avancement: 4,
    latitude: 45.76850,
    longitude: 4.88600
  },
  {
    nom: 'Les fourmis sarthoises',
    adresse: '89 rue Gambetta',
    ville: 'Le Mans',
    departement: '72',
    pays: 'France',
    logo: 'fourmis_sarthoise.jpg',
    site_web: 'http://www.lesfourmissarthoises.fr',
    courriel: 'mailto:contact@lesfourmissarthoises.fr',
    facebook: 'https://www.facebook.com/Les-fourmis-sarthoises-Super-Coop-Le-Mans-113575293764329',
    avancement: 4,
    latitude: 48.007107,
    longitude: 0.189676
  },
  {
    nom: "Eko-Syst'M",
    adresse: '572 boulevard Henry Bordeaux',
    ville: 'Chambéry',
    departement: '73',
    pays: 'France',
    logo: 'ekosystm.webp',
    site_web: 'https://www.ekosystm.com/',
    courriel: 'contact@ekosystm.com',
    facebook: 'https://www.facebook.com/EkosystM',
    avancement: 5,
    latitude: 45.56864,
    longitude: 5.90300
  },
  {
    nom: 'Alpar Coop',
    adresse: '7 Rue du Vieux Moulin, Meythet',
    ville: 'Annecy',
    departement: '74',
    pays: 'France',
    logo: 'alpar.jpg',
    site_web: 'https://www.alpar.fr/',
    courriel: 'contact@alpar.fr',
    facebook: 'https://www.facebook.com/alparcoop/',
    avancement: 4,
    latitude: 45.92011,
    longitude: 6.08801
  },
  {
    nom: 'Les 400 Coop',
    adresse: '65 Boulevard de Charonne',
    ville: 'Paris XIème',
    departement: '75',
    pays: 'France',
    logo: '400coop.png',
    site_web: 'https://les400coop.fr/',
    courriel: 'contact@les400coop.fr',
    facebook: 'https://www.facebook.com/les400coop/',
    avancement: 4,
    latitude: 48.85362,
    longitude: 2.39629
  },
  {
    nom: 'Coop 14',
    adresse: '70 boulevard Jourdan',
    ville: 'Paris XIVème',
    departement: '75',
    pays: 'France',
    logo: 'coop14.png',
    site_web: 'https://coop14.fr/',
    courriel: 'contact@coop14.fr',
    facebook: 'https://www.facebook.com/coop14paris',
    avancement: 4,
    latitude: 48.82267,
    longitude: 2.32901
  },
  {
    nom: 'La Louve',
    adresse: '116, rue des Poissonniers',
    ville: 'Paris XVIIIème',
    departement: '75',
    pays: 'France',
    logo: 'Louve.svg',
    site_web: 'https://cooplalouve.fr/',
    courriel: 'info@cooplalouve.fr',
    facebook: 'https://www.facebook.com/CoopLaLouve',
    avancement: 5,
    latitude: 48.89444,
    longitude: 2.35306
  },
  {
    nom: 'Cago',
    adresse: '59 Rue Stephenson',
    ville: 'Paris XVIIIème',
    departement: '75',
    pays: 'France',
    logo: 'cago.png',
    site_web: 'https://coopaparis.wordpress.com/',
    courriel: 'communication@coopaparis.fr',
    facebook: 'https://www.facebook.com/coopalimentairegouttedor/',
    avancement: 4,
    latitude: 48.88984,
    longitude: 2.35577
  },
  {
    nom: 'La Source',
    adresse: '4 rue Félix Terrier, 75020 Paris',
    ville: 'Paris XXème',
    departement: '75',
    pays: 'France',
    logo: 'la_source.png',
    site_web: 'http://cooplasource.fr/',
    courriel: 'contact@cooplasource.fr',
    facebook: 'https://www.facebook.com/cooplasource/',
    avancement: 4,
    latitude: 48.85731,
    longitude: 2.41086
  },
  {
    nom: 'jachetemonsupermarche',
    adresse: '',
    ville: 'Dieppe',
    departement: '76',
    pays: 'France',
    logo: 'logo_serre_citoyenne.png',
    site_web: 'https://jachetemonsupermarche.com/',
    courriel: 'contact@laserrecitoyenne.fr',
    avancement: 1,
    latitude: 49.9213789,
    longitude: 1.0739232
  },
  {
    nom: 'La mouette',
    adresse: '145, rue du Maréchal Joffre<br>76600 Le Havre',
    ville: 'Le Havre',
    departement: '76',
    pays: 'France',
    logo: 'la_mouette.jpg',
    courriel: 'epicerie.cooperative@gmail.com',
    facebook: 'https://www.facebook.com/LaMouette.epicerie.coop.havraise/',
    avancement: 4,
    latitude: 49.50015,
    longitude: 0.12778
  },
  {
    nom: 'KissiKol',
    adresse: '11-13 rue Saint Vivien, 76000 Rouen',
    ville: 'Rouen',
    departement: '76',
    pays: 'France',
    logo: 'kissikol.png',
    site_web: 'http://magasincooperatifrouen.fr',
    courriel: 'kissikol@ik.me',
    facebook: 'https://www.facebook.com/Magasin-coop%C3%A9ratif-et-participatif-%C3%A0-ROUEN-105373297971520',
    avancement: 3,
    latitude: 49.44242,
    longitude: 1.10561
  },
  {
    nom: 'Valcoop',
    adresse: '4 All. Emile Reynaud <br>77200 Torcy',
    ville: 'Torcy',
    departement: '77',
    pays: 'France',
    logo: 'valcoop.jpg',
    site_web: 'https://www.valcoop.fr/',
    courriel: 'contact@valcoop.fr',
    facebook: 'https://www.facebook.com/Valcoop-713079712233414/',
    avancement: 4,
    latitude: 48.83313,
    longitude: 2.66131
  },
  {
    nom: 'Cooplicot',
    adresse: '3bis, rue de la Saussaie',
    ville: 'Moret-sur-Loing',
    departement: '77',
    pays: 'France',
    logo: 'Cooplicot.png',
    site_web: 'http://cooplicot.fr/',
    courriel: 'cooplicot@gmail.com',
    facebook: 'https://www.facebook.com/Cooplicot/',
    avancement: 3,
    latitude: 48.37344,
    longitude: 2.82323
  },
  {
    nom: 'Le chaudron coop',
    adresse: '5 Rue de Louveciennes',
    ville: 'Le Chesnay',
    departement: '78',
    pays: 'France',
    logo: 'logo_chaudron.png',
    site_web: 'http://lechaudroncoop.fr',
    courriel: 'info@lechaudroncoop.fr',
    facebook: 'https://www.facebook.com/lechaudroncoop/',
    avancement: 3,
    latitude: 48.82640,
    longitude: 2.13777
  },
  {
    nom: 'Pop la coop',
    adresse: '46 Chem. de Montval à la Montagne<br>78160 Marly-le-Roi',
    ville: 'Marly-le-roi',
    departement: '78',
    pays: 'France',
    logo: 'poplacoop.jpeg',
    site_web: 'https://poplacoop.fr/',
    courriel: 'info@poplacoop.fr',
    facebook: 'https://www.facebook.com/POPLACOOP/',
    instagram: 'https://www.instagram.com/poplacoop/',
    avancement: 4,
    latitude: 48.87371,
    longitude: 2.08255
  },
  {
    nom: 'epi castelforain',
    adresse: '1, place St Christophe',
    ville: 'Chateaufort',
    departement: '78',
    pays: 'France',
    logo: 'lepi.png',
    site_web: 'https://www.monepi.fr/castelfortain',
    courriel: 'contact@lepicastelfortain.fr',
    facebook: 'https://www.facebook.com/lepicastelfortain/',
    avancement: 4,
    latitude: 48.73654,
    longitude: 2.09161
  },
  {
    nom: 'le peuplié',
    adresse: '161, rue Dejean',
    ville: 'Amiens',
    departement: '80',
    pays: 'France',
    logo: 'lepeuplie.jpg',
    site_web: 'http://www.lepeuplie.org/',
    courriel: 'contact@lepeuplie.org',
    avancement: 4,
    latitude: 49.89002,
    longitude: 2.32389
  },
  {
    nom: 'Les amis de la CASA',
    adresse: '16 rue Emile Grand',
    ville: 'Albi',
    departement: '81',
    pays: 'France',
    logo: 'les_amis_de_casa.jpg',
    site_web: 'http://les-amis-de-la-casa.forumactif.com/',
    courriel: 'lesamisdelacasa81@gmail.com',
    facebook: 'https://www.facebook.com/Les-amis-de-la-CASA-144243456174379/',
    avancement: 4,
    latitude: 43.93032,
    longitude: 2.14615
  },
  {
    nom: 'La coop sur mer',
    adresse: '270 Avenue Général Pruneau',
    ville: 'Toulon',
    departement: '83',
    pays: 'France',
    logo: 'coop_sur_mer.jpg',
    site_web: 'http://lacoopsurmer.fr/',
    courriel: 'bonjour@lacoopsurmer.fr',
    facebook: 'https://www.facebook.com/LaCoopSurMer/',
    avancement: 5,
    latitude: 43.11985,
    longitude: 5.95289
  },
  {
    nom: 'La cerise sur le Gapeau',
    adresse: '136 Rue du Partégal<br>83210 La Farlède',
    ville: 'La Farlède',
    departement: '83',
    pays: 'France',
    logo: 'cerise_gapeau.png',
    site_web: 'https://www.cooplacerise.fr/',
    courriel: 'contact@cooplacerise.fr',
    facebook: 'https://www.facebook.com/lacerisesurlegapeau/',
    avancement: 4,
    latitude: 43.17083,
    longitude: 6.03964
  },
  {
    nom: "Les Pot'iront",
    adresse: '38 rue de trans',
    ville: 'Draguignan',
    departement: '83',
    pays: 'France',
    logo: 'Les_Pot_iront_new.png',
    site_web: 'https://coop-lespotiront.fr/',
    courriel: 'lespotiront83@gmail.com',
    facebook: 'https://www.facebook.com/cooperativepotiront/',
    avancement: 4,
    latitude: 43.53779,
    longitude: 6.467465
  },
  {
    nom: "Les Pot'iront",
    adresse: '753 boulevad de la Mer',
    ville: 'Fréjus',
    departement: '83',
    pays: 'France',
    logo: 'Les_Pot_iront_new.png',
    site_web: 'https://coop-lespotiront.fr/',
    courriel: 'lespotiront83@gmail.com',
    facebook: 'https://www.facebook.com/cooperativepotiront/',
    avancement: 4,
    latitude: 43.422619,
    longitude: 6.742483
  },
  {
    nom: 'Gem la coop',
    adresse: '49 Rue Alexandre Blanc<br>84000 Avignon',
    ville: 'Avignon',
    departement: '84',
    pays: 'France',
    logo: 'gemlacoop.png',
    site_web: 'http://gem-la-coop.org/',
    courriel: 'contact@gem-la-coop.org',
    facebook: 'https://www.facebook.com/lesamiesgemlacoop/',
    avancement: 4,
    latitude: 43.94053,
    longitude: 4.82196
  },
  {
    nom: 'Lalouet coop',
    adresse: '113 rue nationale',
    ville: 'Les Herbiers',
    departement: '85',
    pays: 'France',
    logo: 'lalouette.png',
    site_web: 'http://www.lalouetcoop.fr/',
    courriel: 'contact@lalouetcoop.fr',
    facebook: 'https://www.facebook.com/LalouetCoop/',
    avancement: 5,
    latitude: 46.86902,
    longitude: -1.00104
  },
  {
    nom: 'Le baudet',
    adresse: '17 place Henri Barbusse',
    ville: 'Poitiers',
    departement: '86',
    pays: 'France',
    logo: 'le_baudet.jpg',
    site_web: 'https://lebaudet.fr/',
    courriel: 'infos@lebaudet.fr',
    facebook: 'https://www.facebook.com/LeBaudetduPoitou/',
    avancement: 4,
    latitude: 46.57613,
    longitude: 0.33847
  },
  {
    nom: "L'Ep'autre",
    adresse: '14 rue Jean Jacques Rousseau',
    ville: 'Juvisy-sur-Orge',
    departement: '91',
    pays: 'France',
    logo: 'epautre.png',
    site_web: 'https://epautre.fr/',
    courriel: 'contact@epautre.fr',
    facebook: 'https://www.facebook.com/Ep.autre',
    avancement: 3,
    latitude: 48.68521,
    longitude: 2.37678
  },
  {
    nom: 'La French Coop',
    adresse: '23 rue de Bretagne',
    ville: 'Asnières-sur-Seine',
    departement: '92',
    pays: 'France',
    logo: 'french_coop.jpg',
    site_web: 'https://lafrenchcoop.fr/site/',
    courriel: 'lesamisdelafrenchcoop@gmail.com',
    facebook: 'https://www.facebook.com/lafrenchcoop/',
    avancement: 4,
    latitude: 48.90514,
    longitude: 2.28285
  },
  {
    nom: 'La Coop Bio du Pré',
    adresse: '2 rue Danton',
    ville: 'Le Pré-Saint-Gervais',
    departement: '93',
    pays: 'France',
    logo: 'La_coop_du_pre.jpg',
    courriel: 'coopdupre@gmail.com',
    facebook: 'https://www.facebook.com/coopdupre/',
    avancement: 2,
    latitude: 48.88416,
    longitude: 2.40373
  },
  {
    nom: 'La caravane',
    adresse: '23, rue Gaston Lauriau',
    ville: 'Montreuil',
    departement: '93',
    pays: 'France',
    logo: 'caravane.png',
    site_web: 'http://lacaravanecoop.fr/',
    courriel: 'contact@lacaravanecoop.fr',
    facebook: 'https://www.facebook.com/Lacaravanecoop',
    avancement: 4,
    latitude: 48.85985,
    longitude: 2.44549
  },
  {
    nom: "Coop'cot",
    adresse: 'Centre Commercial l’Échat<br>92 Avenue du Général de Gaulle',
    ville: 'Créteil',
    departement: '94',
    pays: 'France',
    logo: 'coopcot.png',
    site_web: 'http://coopcot.fr/',
    courriel: 'contact@coopcot.fr',
    facebook: 'https://fr-fr.facebook.com/supermarchecooperatif94/',
    avancement: 3,
    latitude: 48.78692,
    longitude: 2.44684
  },
  {
    nom: 'Coquelicoop',
    adresse: '43 rue Émile Zola',
    ville: 'Fresnes',
    departement: '94',
    pays: 'France',
    logo: 'coquelicoop.png',
    site_web: 'https://coquelicoop.fr/',
    courriel: 'contact@coquelicoop.fr',
    facebook: 'https://www.facebook.com/coquelicoop.fr/',
    avancement: 4,
    latitude: 48.76133,
    longitude: 2.32645
  },
  {
    nom: 'Coop les bains',
    adresse: '22 bis Rue de Malleville<br>95880 Enghien-les-Bains',
    ville: 'Enghien-les-Bains',
    departement: '95',
    pays: 'France',
    logo: 'coop_les_bains.png',
    site_web: 'https://www.cooplesbains.fr/',
    courriel: 'contact@cooplesbains.fr',
    facebook: 'https://www.facebook.com/coopenghien/',
    avancement: 4,
    latitude: 48.96901,
    longitude: 2.30729
  },
  {
    nom: 'La Calebasse',
    adresse: '',
    ville: 'Guadeloupe',
    departement: '971',
    pays: 'France',
    logo: 'la_calebasse.jpg',
    courriel: 'lacalebasse.coop@gmail.com',
    facebook: 'https://www.facebook.com/lacalebasse971/',
    avancement: 2,
    latitude: 16.2350099,
    longitude: -61.560867
  },
  {
    nom: 'La coop à nous',
    adresse: '3 impasse uitoe',
    ville: 'Nouméa',
    departement: '988',
    pays: 'France',
    logo: 'lacoopanous.jpg',
    site_web: 'http://lacoopanous.nc/',
    courriel: 'lacoopanous@gmail.com',
    facebook: 'https://www.facebook.com/coopanous/',
    avancement: 3,
    latitude: -22.26569,
    longitude: 166.47021
  },
  {
    nom: 'BEES Coop',
    adresse: '19 rue van hove – 1030 Schaerbeek',
    ville: 'Bruxelles',
    departement: '',
    pays: 'Belgique',
    logo: 'bees_coop.png',
    site_web: 'http://bees-coop.be/',
    courriel: 'contact@bees-coop.be',
    facebook: 'https://www.facebook.com/CooperativeBEES/',
    avancement: 5,
    latitude: 50.85690,
    longitude: 4.37731
  },
  {
    nom: 'WooCoop',
    adresse: '55 avenue des pâquerettes',
    ville: 'Waterloo',
    departement: '',
    pays: 'Belgique',
    logo: 'woocoop.jpg',
    site_web: 'http://www.woocoop.be/',
    courriel: 'info@woocoop.be',
    facebook: 'https://www.facebook.com/WooCoop/',
    avancement: 4,
    latitude: 50.71833,
    longitude: 4.38585
  },
  {
    nom: 'Oufticoop',
    adresse: '10 Rue Curtius',
    ville: 'Liège',
    departement: '',
    pays: 'Belgique',
    logo: 'outficoop.jpg',
    site_web: 'https://www.oufticoop.be/',
    courriel: 'contact@oufticoop.be',
    facebook: 'https://www.facebook.com/Oufticoop-2003796329891655',
    avancement: 4,
    latitude: 50.64565,
    longitude: 5.58813
  },
  {
    nom: 'Coopeco',
    adresse: "12 Rue de l'Abattoir",
    ville: 'Charleroi',
    departement: '',
    pays: 'Belgique',
    logo: 'coopeco.svg',
    site_web: 'https://coopeco-supermarche.be/',
    courriel: 'info@coopeco-supermarche.be',
    facebook: 'https://www.facebook.com/coopecosupermarche/',
    avancement: 4,
    latitude: 50.40678,
    longitude: 4.4011
  },
  {
    nom: 'Vervicoop',
    adresse: 'rue de Heusy 30',
    ville: 'Verviers',
    departement: '',
    pays: 'Belgique',
    logo: 'vervicoop.png',
    site_web: 'https://vervicoop.be/',
    courriel: 'info@vervicoop.be',
    facebook: 'https://www.facebook.com/vervicoop/',
    avancement: 4,
    latitude: 50.59220,
    longitude: 5.86691
  },
  {
    nom: 'Bloum',
    adresse: '174 Rue Des Alliés',
    ville: 'Forest',
    departement: '',
    pays: 'Belgique',
    logo: 'bloum_logo.png',
    site_web: 'https://bloum.be/',
    courriel: 'info@bloum.be',
    facebook: 'https://www.facebook.com/bloumcoop1190/',
    avancement: 4,
    latitude: 50.81946,
    longitude: 4.32684
  },
  {
    nom: 'Macavrac',
    adresse: 'Rue des Fontaines 51<br>1300 Wavre',
    ville: 'Wavre',
    departement: '',
    pays: 'Belgique',
    logo: 'macavrac.png',
    site_web: 'https://macavrac.be/',
    courriel: 'miam@macavrac.be',
    facebook: 'https://www.facebook.com/Macavrac/',
    avancement: 4,
    latitude: 50.71466,
    longitude: 4.60906
  },
  {
    nom: 'Co-é-sion - La Cagette 1791',
    adresse: '13 route de Sion',
    ville: 'Champlan',
    departement: '',
    pays: 'Suisse',
    logo: 'coesion.png',
    site_web: 'https://co-e-sion.ch/',
    courriel: 'contact@co-e-sion.ch',
    facebook: 'https://www.facebook.com/coopcoesion/',
    avancement: 4,
    latitude: 46.24560,
    longitude: 7.37079
  },
  {
    nom: 'Le Nid',
    adresse: 'Chemin du 23 Août 5',
    ville: 'Genève',
    departement: '',
    pays: 'Suisse',
    logo: 'lenid.png',
    site_web: 'https://lenid.ch/',
    courriel: 'info@lenid.ch',
    facebook: 'https://www.facebook.com/lenidgeneve/',
    avancement: 4,
    latitude: 46.20274,
    longitude: 6.13502
  },
  {
    nom: 'La fève',
    adresse: 'Esplanade des Récréations 19<br>1217 Meyrin',
    ville: 'Meyrin',
    departement: '',
    pays: 'Suisse',
    logo: 'la_feve.jpg',
    site_web: 'https://la-feve.ch/',
    courriel: 'info@spp-vergers.ch',
    facebook: 'https://www.facebook.com/SupermarcheParticipatifPaysan/',
    avancement: 4,
    latitude: 46.23182,
    longitude: 6.07173
  },
  {
    nom: 'Système B',
    adresse: '1 Rue du Roc',
    ville: 'Neuchatel',
    departement: '',
    pays: 'Suisse',
    logo: 'systeme_B.png',
    site_web: 'https://systeme-b.ch/',
    courriel: 'contact@systeme-b.ch',
    facebook: 'https://www.facebook.com/SystemeB.ch/',
    avancement: 4,
    latitude: 46.99855,
    longitude: 6.93699
  },
  {
    nom: 'Chez Emmy',
    adresse: "20 Grand'Rue",
    ville: 'St-Blaise',
    departement: '',
    pays: 'Suisse',
    logo: 'chez_Emmy.svg',
    site_web: 'https://about.chez-emmy.ch/',
    courriel: 'epicerie@chez-emmy.ch',
    avancement: 4,
    latitude: 47.01291,
    longitude: 6.98710
  },
  {
    nom: 'L\'épicerie d\'à côté',
    adresse: 'Rue du Tertre 12',
    ville: 'Neuchâtel',
    departement: '',
    pays: 'Suisse',
    logo: 'lepiceriedacote.svg',
    site_web: 'https://lepiceriedacote.ch/',
    courriel: 'contact@lepiceriedacote.ch',
    facebook: 'https://www.facebook.com/lepiceriedacote',
    avancement: 4,
    latitude: 46.9944222,
    longitude: 6.9306194
  },
  {
    nom: 'Epicentre',
    adresse: 'Rue Louis-Favre 36',
    ville: 'Boudry',
    departement: '',
    pays: 'Suisse',
    logo: 'epicentreboudry.svg',
    site_web: 'https://epicentre-boudry.ch/',
    courriel: 'info@epicentre-boudry.ch',
    facebook: 'https://www.facebook.com/EpicerieVracBoudry/',
    avancement: 4,
    latitude: 46.9488861,
    longitude: 6.8358758
  },
  {
    nom: 'Epicoop',
    adresse: 'Rue des Marronniers 3B',
    ville: 'Vevey',
    departement: '',
    pays: 'Suisse',
    logo: 'epicoop.svg',
    site_web: 'https://epicoop.ch',
    courriel: 'contact@epicoop.ch',
    facebook: 'https://www.facebook.com/EpicoopRiviera/',
    avancement: 4,
    latitude: 46.4660495,
    longitude: 6.84262831
  },
  {
    nom: 'Coupe Circuit',
    adresse: 'Jardins-de-Prélaz 8',
    ville: 'Lausanne',
    departement: '',
    pays: 'Suisse',
    logo: 'coupecircuit.svg',
    site_web: 'https://coupe-circuit.ch/',
    courriel: 'epicerie@coupe-circuit.ch',
    facebook: 'https://www.facebook.com/epicerie.coupe.circuit',
    avancement: 4,
    latitude: 46.5268883,
    longitude: 6.6113325
  },
  {
    nom: 'Le Jardin Vivant',
    adresse: 'Av. Louis-Ruchonnet 33',
    ville: 'Lausanne',
    departement: '',
    pays: 'Suisse',
    logo: 'jardinvivant.svg',
    site_web: 'https://lejardinvivant.ch/',
    courriel: 'coop@lejardinvivant.ch',
    facebook: 'https://www.facebook.com/lejardinvivantlausanne',
    avancement: 4,
    latitude: 46.5190778,
    longitude: 6.6243197
  },
  {
    nom: 'Le Rucher',
    adresse: 'Rue des 22-Cantons 17',
    ville: 'La Chaux-de-Fonds',
    departement: '',
    pays: 'Suisse',
    logo: 'lerucher.png',
    site_web: 'https://lerucher.ch',
    courriel: 'epicerie@lerucher.ch',
    facebook: '',
    avancement: 4,
    latitude: 47.111300,
    longitude: 6.825810
  },
  {
    nom: 'Le Marché Saint-Germain',
    adresse: 'Route de Courgenay 18',
    ville: 'Porrentruy',
    departement: '',
    pays: 'Suisse',
    logo: 'lemarchesaintgermain.svg',
    site_web: 'https://lemarchesaintgermain.ch/',
    courriel: 'info@lemarchesaintgermain.ch',
    facebook: 'https://www.facebook.com/lemarchesaintgermain',
    avancement: 4,
    latitude: 47.4158272,
    longitude: 7.0798611
  },
  {
    nom: 'La Vracrie',
    adresse: 'Route Principale 90',
    ville: 'Praz',
    departement: '',
    pays: 'Suisse',
    logo: 'lavracrie.svg',
    site_web: 'https://lavracrie.ch/',
    courriel: 'info@lavracrie.ch',
    facebook: 'https://www.facebook.com/VracrieVully',
    avancement: 4,
    latitude: 46.9553806,
    longitude: 7.1021961
  },
  {
    nom: 'La Vorace',
    adresse: 'Route de Praz-Véguey 29',
    ville: 'Chavannes-près-Renens',
    departement: '',
    pays: 'Suisse',
    logo: 'levorace.svg',
    site_web: 'https://levorace.ch/',
    courriel: 'info@levorace.ch',
    facebook: 'https://www.facebook.com/levorace.epicerie',
    avancement: 4,
    latitude: 46.5249147,
    longitude: 6.5748100
  },
  {
    nom: 'Le Local',
    adresse: 'Chemin du Midi 8',
    ville: 'Nyon',
    departement: '',
    pays: 'Suisse',
    logo: 'lelocalnyon.png',
    site_web: 'https://lelocal-nyon.ch/',
    courriel: 'info@lelocal-nyon.ch',
    facebook: 'https://www.facebook.com/Lelocalnyon/',
    avancement: 4,
    latitude: 46.3818228,
    longitude: 6.2356514
  },
  {
    nom: 'Tabernam',
    adresse: '',
    ville: 'Yverdon',
    departement: '',
    pays: 'Suisse',
    logo: 'tabernam.png',
    site_web: 'https://tabernam.ch',
    courriel: 'info@tabernam.ch',
    facebook: 'https://www.facebook.com/tabernam.epicerie',
    avancement: 4,
    latitude: 46.788097,
    longitude: 6.648250
  },
  {
    nom: 'La Brouette',
    adresse: 'Av. d\'Echallens 79',
    ville: 'Lausanne',
    departement: '',
    pays: 'Suisse',
    logo: 'labrouette.png',
    site_web: 'https://labrouette.ch',
    courriel: 'info@labrouette.ch',
    facebook: 'https://www.facebook.com/epicerielabrouette',
    avancement: 5,
    latitude: 46.528140,
    longitude: 6.615700
  },
  {
    nom: 'La Canopée',
    adresse: 'Rue de Mura 27',
    ville: 'Muraz (Sierre)',
    departement: '',
    pays: 'Suisse',
    logo: 'lacanopee.png',
    site_web: 'https://epicerielacanopee.ch/',
    courriel: 'epiceriemuraz@gmail.com',
    avancement: 4,
    latitude: 46.2980042,
    longitude: 7.5292742
  },
  {
    nom: 'Les Enfants de la Terre',
    adresse: '24, rue Frédéric-Soguel',
    ville: 'Cernier',
    departement: '',
    pays: 'Suisse',
    logo: 'lesenfantsdelaterre.webp',
    site_web: 'https://www.lesenfantsdelaterre.ch/site/',
    courriel: 'epicerie@lesenfantsdelaterre.ch',
    avancement: 4,
    latitude: 47.0595840,
    longitude: 6.90387011
  },
  {
    nom: 'Les P\'tits Pois',
    adresse: 'Promenade de l\'Eglantine 1',
    ville: 'Morges',
    departement: '',
    pays: 'Suisse',
    logo: 'lesptitspois.jpg',
    site_web: 'https://lesptitspois.ch/',
    courriel: '',
    avancement: 4,
    latitude: 46.51195213,
    longitude: 6.484526483
  },
  {
    nom: "The People's <br>Supermarket",
    adresse: "72-78 Lamb's Conduit Street",
    ville: 'Londres',
    departement: '',
    pays: 'Angleterre',
    logo: 'thepeoplessupermarket.jpg',
    site_web: 'http://www.thepeoplessupermarket.org/',
    courriel: 'gemma@thepeoplessupermarket.org',
    facebook: 'https://www.facebook.com/thepeoplessupermarket/',
    avancement: 5,
    latitude: 51.5226,
    longitude: -0.11875
  },
  {
    nom: 'AlterCoop',
    adresse: '18A & 18D rue de la cimenterie 1337 Luxembourg',
    ville: 'Luxembourg',
    departement: '',
    pays: 'Luxembourg',
    logo: 'altercoop_logo_final.png',
    site_web: 'http://www.altercoop.lu/',
    courriel: 'contact@altercoop.lu',
    facebook: 'https://www.facebook.com/AlterCoopLuxembourg/',
    avancement: 4,
    latitude: 49.641337,
    longitude: 6.135053
  },
  {
    nom: 'Camilla',
    adresse: '8 via Vincenzo Casciarolo',
    ville: 'Bologne',
    departement: '',
    pays: 'Italie',
    logo: 'camilla.png',
    site_web: 'https://camilla.coop/',
    courriel: 'info@camilla.coop',
    facebook: 'https://www.facebook.com/cooperativacamilla/',
    avancement: 5,
    latitude: 44.50582,
    longitude: 11.36045
  },
  {
    nom: 'Lokatten Supermarket',
    adresse: '',
    ville: 'Stockholm',
    departement: '',
    pays: 'Suède',
    logo: 'lokatten.png',
    site_web: 'https://www.lokatten.org/',
    courriel: 'contact@lokatten.org',
    facebook: 'https://www.facebook.com/groups/1503136399808982/',
    avancement: 3,
    latitude: 59.3255,
    longitude: 18.0711
  },
  {
    nom: 'Rizoma coop',
    adresse: 'Beco do Rosendo 8',
    ville: 'Lisboa',
    departement: '',
    pays: 'Portugal',
    logo: 'rizoma.svg',
    site_web: 'https://www.rizomacoop.pt/',
    courriel: 'geral@rizomacoop.pt',
    facebook: 'https://www.facebook.com/rizomacoop.pt',
    avancement: 4,
    latitude: 38.713767,
    longitude: -9.136232
  },
  {
    nom: 'Dublin FoodCoop',
    adresse: 'Unit 1 Building 1<br>The Old Chocolate Factory<br>Kilmainham Square, Inchicore road',
    ville: 'Dublin',
    departement: '',
    pays: 'Irlande',
    logo: 'dublin_foodcoop.jpg',
    site_web: 'http://magasincooperatifrouen.fr',
    courriel: 'info@dublinfood.coop',
    facebook: 'https://www.facebook.com/DublinFoodCoop/',
    avancement: 5,
    latitude: 53.34239,
    longitude: -6.31017
  },
  {
    nom: 'The Urban Co-Op',
    adresse: '8 Eastway Business Park Limerick<br>Limerick V94 N7D3',
    ville: 'Limerick V94 N7D3',
    departement: '',
    pays: 'Irlande',
    logo: 'the_urban_coop.png',
    site_web: 'https://www.theurbanco-op.ie/',
    courriel: 'info@theurbanco-op.ie',
    facebook: 'https://www.facebook.com/TheUrbanCoOp/',
    avancement: 5,
    latitude: 52.64936,
    longitude: -8.58885
  },
  {
    nom: 'Belfast Food Co-op',
    adresse: '29 Chichester Avenue BT15 5EH',
    ville: 'Belfast',
    departement: '',
    pays: 'Irlande du Nord',
    logo: 'belfast.svg',
    site_web: 'https://belfast.coop/',
    courriel: 'belfastfoodcoopni@gmail.com',
    facebook: 'https://www.facebook.com/belfastfoodcoop/',
    avancement: 5,
    latitude: 54.63048,
    longitude: -5.94133
  },
  {
    nom: 'La Osa',
    adresse: 'Av. de Asturias, 57<br>28029 Madrid',
    ville: 'Madrid',
    departement: '',
    pays: 'Espagne',
    logo: 'la_osa_es.jpg',
    site_web: 'https://laosa.coop/',
    courriel: 'hola@laosa.coop',
    facebook: 'https://www.facebook.com/LaOsaCoop/',
    avancement: 5,
    latitude: 40.47141,
    longitude: -3.69835
  },
  {
    nom: 'foodcoops.de',
    ville: 'Pays Allemagne',
    departement: '',
    pays: 'Allemagne',
    logo: 'foodcoop_bundes_ag.png',
    site_web: 'http://www.oekoop.de/bag_contenido-4.8/cms/front_content.php?idcat=25',
    avancement: 5,
    latitude: 51.591,
    longitude: 10.545
  },
  {
    nom: 'foodcoops.at',
    ville: 'Pays Autriche',
    departement: '',
    pays: 'Autriche',
    logo: 'foodcops_at.png',
    site_web: 'https://foodcoops.at/bestehende-foodcoops/',
    avancement: 5,
    latitude: 47.881,
    longitude: 14.770
  },
  {
    nom: 'Le détour',
    adresse: '1900 rue le Ber local 102 <br> Montréal, QC H3K 2A4',
    ville: 'Montréal',
    departement: '',
    pays: 'Canada',
    logo: 'logo_le_detour_canada.png',
    site_web: 'https://wordpress.epicerieledetour.org/',
    courriel: 'info@epicerieledetour.org',
    facebook: 'https://www.facebook.com/epicerieledetour',
    avancement: 4,
    latitude: 45.48118,
    longitude: -73.55223
  },
  {
    nom: "L'ortie folle",
    adresse: 'Montreal, QC, Canada, Quebec',
    ville: 'Montréal',
    departement: '',
    pays: 'Canada',
    logo: 'logo_ortiefolle_canada.png',
    site_web: 'https://ortiefolle.org',
    courriel: 'epiceriecoopmtl@gmail.com',
    facebook: 'https://www.facebook.com/lortiefolle',
    avancement: 2,
    latitude: 45.39785,
    longitude: -73.8122
  },
  {
    nom: 'Coop Lib',
    adresse: '"Epiceries libres"',
    departement: '',
    pays: 'France',
    logo: 'cooplib.png',
    site_web: 'https://cooplib.fr/',
    avancement: 4,
    latitude: 46.110,
    longitude: -4.264
  }
]
