const supermarches =[
   {
      "nom": "Park Slop<br>Food Coop",
      "departement":"US",
      "ville":"New York",
      "adresse":"",
      "logo":"food_coop.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://www.foodcoop.com/",
      "courriel":"",
      "facebook":"",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":40.6748669,
      "longitude":-73.9789982
   },
   
   {
      "nom": "Nice Coop",
      "departement":"06",
      "ville":"Nice",
      "adresse":"",
      "logo":"logo-NC.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://nicecoop.fr/",
      "courriel":"nicecoop06@gmail.com",
      "facebook":"https://www.facebook.com/nicecoop2/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":43.7091454,
      "longitude":7.2317066
   },

   {
      "nom": "Coop La Meute",
      "departement":"06",
      "ville":"Grasse",
      "adresse":"59 avenue de la liberation",
      "logo":"la_meute.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://www.cooplameute.fr/",
      "courriel":"contact@cooplameute.fr",
      "facebook":"https://www.facebook.com/cooplameute/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":43.6464686, 
      "longitude":6.9140306 
   },

   {
      "nom": "Marcasserie",
      "departement":"08",
      "ville":"Charleville-Mézières",
      "adresse":"",
      "logo":"marcasserie.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://marcasserie.org/",
      "courriel":"contact@marcasserie.org",
      "facebook":"https://www.facebook.com/marcasserie/",     
      "statuts":"",
      "avancement":3,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":49.767542, 
      "longitude":4.718328  
   },

   {
      "nom": "Super Cafoutch",
      "departement":"13",
      "ville":"Marseille 2",
      "adresse":"14 rue Louis Astouin",
      "logo":"super_cafoutch.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://supercafoutch.fr/",
      "courriel":"contact@supercafoutch.fr",
      "facebook":"https://www.facebook.com/supercafoutch/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":43.3011168, 
      "longitude":5.3713767 
   },

   {
      "nom": "Court circuit 21",
      "departement":"21",
      "ville":"Dijon",
      "adresse":"2 rue des Corroyeurs",
      "logo":"court-circuit21.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://supermarchecoop.wixsite.com/dijon",
      "courriel":"contact@magasin-cooperatif-dijon.org",
      "facebook":"https://www.facebook.com/courtcircuit21/",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":47.3150932, 
      "longitude":5.0315365  
   },

   {
      "nom": "Ti Coop",
      "departement":"29",
      "ville":"Brest",
      "adresse":"1 rue Louis Pidoux, Bâtiment E",
      "logo":"ti_coop.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://ticoop.fr/",
      "courriel":"contact@ticoop.fr",
      "facebook":"https://www.facebook.com/TiCoopBrest",     
      "statuts":"",
      "avancement":2,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.3963874, 
      "longitude":-4.4678621
   },  
   {
      "nom": "La chouette coop",
      "departement":"31",
      "ville":"Toulouse",
      "adresse":"12 avenue de Lyon",
      "logo":"La_Chouette.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://lachouettecoop.fr/",
      "courriel":"contact@lachouettecoop.fr",
      "facebook":"https://www.facebook.com/lachouettecoop/",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":43.6144677, 
      "longitude":1.4517085  
   },

   {
      "nom": "SuperCoop",
      "departement":"33",
      "ville":"Bordeaux",
      "adresse":"19 rue Oscar et Jean Auriac",
      "logo":"supercoop.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://supercoop.fr/",
      "courriel":"contact@supercoop.fr",
      "facebook":"https://www.facebook.com/supercoopbdx/",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":44.814616, 
      "longitude":-0.5545494  
   },

   {
      "nom": "La cagette",
      "departement":"34",
      "ville":"Montpellier",
      "adresse":"19 avenue Clémenceau",
      "logo":"cagette.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://lacagette-coop.fr/",
      "courriel":"contact@lacagette-coop.fr",
      "facebook":"https://www.facebook.com/LaCagette34",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":43.6039077,
      "longitude":3.8730192
   },

   {
      "nom": "Breizhicoop",
      "departement":"35",
      "ville":"Rennes",
      "adresse":"",
      "logo":"breizhicoop.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://www.breizhicoop.fr/",
      "courriel":"contact@breizhicoop.fr",
      "facebook":"https://www.facebook.com/breizhicoop/",     
      "statuts":"",
      "avancement":2,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.1169194, 
      "longitude":-1.679918  
   },  

   {
      "nom": "L’éléfàn",
      "departement":"38",
      "ville":"Grenoble",
      "adresse":"13, chemin de la Capuche",
      "logo":"Lelefan.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://lelefan.org/",
      "courriel":"contact@lelefan.org",
      "facebook":"https://www.facebook.com/lelefandegrenoble/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":45.1804, 
      "longitude":5.7225724  
   },

   {
      "nom": "La Fourmilière",
      "departement":"42",
      "ville":"Saint-Etienne",
      "adresse":"",
      "logo":"fourmiliere.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://coop-lafourmiliere.fr/",
      "courriel":"contact@coop-lafourmiliere.fr",
      "facebook":"",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":45.435738, 
      "longitude":4.379283  
   },

   {
      "nom": "Scopeli",
      "departement":"44",
      "ville":"Nantes",
      "adresse":"20 Rue de l’Abbé Grégoire,<br> 44 400 Rezé",
      "logo":"scopeli.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://www.scopeli.fr/",
      "courriel":"contact@scopeli.fr",
      "facebook":"https://www.facebook.com/Scopeli/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":47.1953166, 
      "longitude":-1.5705085
   },

   {
      "nom": "La Coop du Coin",
      "departement":"44",
      "ville":"Saint-Nazaire",
      "adresse":"35 Boulevard Gambetta",
      "logo":"coop-du-Coin.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://lacoopducoin-epicerie-cooperative-participative.fr/",
      "courriel":"lesamisdelacoopducoin@gmail.com",
      "facebook":"https://www.facebook.com/lesamisdelacoopducoin/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":47.2776656, 
      "longitude":-2.2174559
   },
   
   {
      "nom": "La coopérette",
      "departement":"45",
      "ville":"Orléans",
      "adresse":"6/10 Avenue F Rabelais<br>Saint Jean de Braye – 45800",
      "logo":"cooperette.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://lacooperette.fr/",
      "courriel":"contact@lacooperette.fr",
      "facebook":"https://www.facebook.com/supermarchecooperatiforleans",     
      "statuts":"",
      "avancement":3,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":47.9073767, 
      "longitude":1.9503179
   },

   {
      "nom": "La coop'agenoise",
      "departement":"47",
      "ville":"Agen",
      "adresse":"",
      "logo":"coop_agenaise.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"",
      "courriel":"supermarchecoopagen@bbox.fr",
      "facebook":"https://www.facebook.com/LaCoopAgenaise/",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":44.2046512, 
      "longitude":0.622364
   },

   {
      "nom": "Ma Coop <br>La Vie au Vert",
      "departement":"48",
      "ville":"Pied-de-Borne",
      "adresse":"",
      "logo":"lavieauvert.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://cdurable.info/-Ma-Coop-La-Vie-au-Vert-75-",
      "courriel":"macoop@cdurable.info",
      "facebook":"https://www.facebook.com/Ma-Coop-La-Vie-au-Vert-515261028532421/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":44.4756718, 
      "longitude":3.9831443
   },
   
   {
      "nom": "coop en Baie",
      "departement":"50",
      "ville":"Avranches/Granville",
      "adresse":"",
      "logo":"coopenbaie.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://coopenbaie.fr/",
      "courriel":"",
      "facebook":"https://www.facebook.com/coopenbaie/",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":48.8418002, 
      "longitude":-1.5822933
   },
   
   {
      "nom": "Grande épicerie<br> générale",
      "departement":"54",
      "ville":"Nancy",
      "adresse":"61 Rue St Nicolas",
      "logo":"grande_epicerie.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://www.grandeepiceriegenerale.fr/",
      "courriel":"contact@grandeepiceriegenerale.fr",
      "facebook":"https://www.facebook.com/GEGNancy/",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.6881942, 
      "longitude":6.1850779  
   },

   {
      "nom": "Coop des Vénètes",
      "departement":"56",
      "ville":"Vannes",
      "adresse":"",
      "logo":"coop_venetes.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://www.coopdesvenetes.bzh/",
      "courriel":"contact@coopdesvenetes.bzh",
      "facebook":"https://www.facebook.com/Coop-des-V%C3%A9n%C3%A8tes-1858337227811822/",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":47.6576484, 
      "longitude":-2.7735705 
   },
   
   {
      "nom": "SuperQuinquin",
      "departement":"59",
      "ville":"Lille",
      "adresse":"15 rue du Prieuré",
      "logo":"superquinquin.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://superquinquin.fr/",
      "courriel":"jarrive@superquinquin.fr",
      "facebook":"https://www.facebook.com/SuperQuinquin-1060478380629115/",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":50.6329804, 
      "longitude":3.0859166
   },

   {
      "nom": "La coop <br>des dômes",
      "departement":"63",
      "ville":"Clermont-Ferrand",
      "adresse":"103 rue d’Aulteribe",
      "logo":"LaCoopDesDomes.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://www.coopdesdomes.fr/",
      "courriel":"contact@coopdesdomes.fr",
      "facebook":"https://www.facebook.com/CoopDesDomes",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":45.8125572, 
      "longitude":3.1264134  
   },

   {
      "nom": "Otsokop",
      "departement":"64",
      "ville":"Bayonne",
      "adresse":"1, avenue de Lattre de Tassigny",
      "logo":"OTSOKOP.PNG",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://www.otsokop.org/",
      "courriel":"contact@otsokop.org",
      "facebook":"https://www.facebook.com/otsokop/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":43.502204, 
      "longitude":-1.4705459  
   },

   {
      "nom": "Coopalim",
      "departement":"67",
      "ville":"Strabourg",
      "adresse":"7 rue Kageneck",
      "logo":"coopalim.png",
      "date_creation":"6 septembre 2017",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://coopalimstrasbourg.com/",
      "courriel":"coopalim@gmail.com",
      "facebook":"https://www.facebook.com/coopalim.strasbourg/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.5842051, 
      "longitude":7.7379942
   },
   
   {
      "nom": "Les Oies <br>Sauvages",
      "departement":"68",
      "ville":"Colmar",
      "adresse":"27 rue du Logelbach",
      "logo":"oies_sauvages.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://cooplesoiessauvages.alsace/",
      "courriel":"contact@CoopLesOiesSauvages.Alsace",
      "facebook":"https://www.facebook.com/CoopLesOiesSauvages/",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.0810342, 
      "longitude":7.3468806
   },
   
   {
      "nom": "Le Panier du<br> Mehlala",
      "departement":"68",
      "ville":"Mulhouse",
      "adresse":"",
      "logo":"mehlala.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://epicerie-participative-mulhouse.fr/",
      "courriel":"contact@epicerie-participative-mulhouse.fr",
      "facebook":"https://www.facebook.com/epicerieparticipativemulhouse/",     
      "statuts":"",
      "avancement":3,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":47.7451964, 
      "longitude":7.3242222
   },
   
   {
      "nom": "Demain",
      "departement":"69",
      "ville":"Lyon",
      "adresse":"95 boulevard des États-Unis",
      "logo":"demain.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://www.demainsupermarche.org/",
      "courriel":"communicationdemain@gmail.com",
      "facebook":"https://www.facebook.com/Demainsupermarche/",     
      "statuts":"",
      "avancement":3,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":45.7305741, 
      "longitude":4.8648604  
   },

   {
      "nom": "Eko-Syst'M",
      "departement":"73",
      "ville":"Chambéry",
      "adresse":"572 boulevard Henry Bordeaux",
      "logo":"ekosystm.webp",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://www.ekosystm.com/",
      "courriel":"contact@ekosystm.com",
      "facebook":"https://www.facebook.com/EkosystM",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":45.5686484, 
      "longitude":5.900733  
   },

   {
      "nom": "Alpar Coop",
      "departement":"74",
      "ville":"Annecy",
      "adresse":"7 Rue du Vieux Moulin, Meythet",
      "logo":"alpar.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://www.alpar.fr/",
      "courriel":"contact@alpar.fr",
      "facebook":"https://www.facebook.com/alparcoop/",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":45.9199, 
      "longitude":6.0881  
   },  

   {
      "nom": "Les 400 Coop",
      "departement":"75",
      "ville":"Paris XIème",
      "adresse":"65 Boulevard de Charonne",
      "logo":"400coop.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://les400coop.fr/",
      "courriel":"contact@les400coop.fr",
      "facebook":"https://www.facebook.com/les400coop/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.8534183, 
      "longitude":2.3943203  
   },

   {
      "nom": "Les grains de sel",
      "departement":"75",
      "ville":"Paris XIIIème",
      "adresse":"",
      "logo":"lesgrainsdesel.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://www.lesgrainsdesel.fr/",
      "courriel":"contact@lesgrainsdesel.fr",
      "facebook":"https://www.facebook.com/Lesgrainsdesel/",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.8305395, 
      "longitude":2.3540165 
   },
   
   {
      "nom": "Cago",
      "departement":"75",
      "ville":"Paris XVIIIème",
      "adresse":"59 Rue Stephenson",
      "logo":"cago.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://coopaparis.wordpress.com/",
      "courriel":"communication@coopaparis.fr",
      "facebook":"https://www.facebook.com/coopalimentairegouttedor/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude": 48.8900312, 
      "longitude":2.3557515  
   },
   
   {
      "nom": "La Louve",
      "departement":"75",
      "ville":"Paris XVIIIème",
      "adresse":"116, rue des Poissonniers",
      "logo":"Louve.svg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://cooplalouve.fr/",
      "courriel":"info@cooplalouve.fr",
      "facebook":"https://www.facebook.com/CoopLaLouve",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":48.8943295, 
      "longitude":2.3508935
  },
   
  {
      "nom": "La source",
      "departement":"75",
      "ville":"Paris XXème",
      "adresse":"",
      "logo":"la_source.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://cooplasource.fr/",
      "courriel":"contact@cooplasource.fr",
      "facebook":"https://www.facebook.com/cooplasource/",     
      "statuts":"",
      "avancement":2,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":48.8689502, 
      "longitude":2.3887822
   },
   
   {
      "nom": "jachetemonsupermarche",
      "departement":"76",
      "ville":"Dieppe",
      "adresse":"",
      "logo":"logo_serre_citoyenne.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://jachetemonsupermarche.com/",
      "courriel":"contact@laserrecitoyenne.fr",
      "facebook":"",
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":49.9213789, 
      "longitude":1.0739232 
   },

   {
      "nom": "Valcoop",
      "departement":"77",
      "ville":"Val Maubuée",
      "adresse":"",
      "logo":"valcoop.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://www.valcoop.fr/",
      "courriel":"contact@valcoop.fr",
      "facebook":"https://www.facebook.com/Valcoop-713079712233414/",
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.8529962, 
      "longitude":2.5944281  
   },

   {
      "nom": "Cooplicot",
      "departement":"77",
      "ville":"More sur loing",
      "adresse":" 2 rue du Clos Blanchet",
      "logo":"Cooplicot.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://cooplicot.fr/",
      "courriel":"",
      "facebook":"https://www.facebook.com/Cooplicot/",     
      "statuts":"",
      "avancement":3,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.3722595, 
      "longitude":2.8123939  
   },

   {
      "nom": "Le chaudron coop",
      "departement":"78",
      "ville":"Versailles",
      "adresse":"2 bis place de Touraine",
      "logo":"logo_chaudron.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://lechaudroncoop.fr",
      "courriel":"info@lechaudroncoop.fr",
      "facebook":"https://www.facebook.com/lechaudroncoop/",     
      "statuts":"",
      "avancement":3,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.8039169, 
      "longitude":2.1602191  
   },

   {
      "nom": "Pop la coop",
      "departement":"78",
      "ville":"Saint-Germain-en-Laye",
      "adresse":"",
      "logo":"poplacoop.jpeg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://poplacoop.fr/",
      "courriel":"info@poplacoop.fr",
      "facebook":"https://www.facebook.com/POPLACOOP/",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.935664, 
      "longitude":2.0363693  
   },

   {
      "nom": "epi castelforain",
      "departement":"78",
      "ville":"Chateaufort",
      "adresse":"1, place St Christophe",
      "logo":"lepi.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://www.monepi.fr/castelfortain",
      "courriel":"contact@lepicastelfortain.fr",
      "facebook":"https://www.facebook.com/lepicastelfortain/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.7367056, 
      "longitude":2.0913428 
   },
   
   {
      "nom": "Les amis de la CASA",
      "departement":"81",
      "ville":"Albi",
      "adresse":"16 rue Emile Grand",
      "logo":"les_amis_de_casa.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://les-amis-de-la-casa.forumactif.com/",
      "courriel":"lesamisdelacasa81@gmail.com",
      "facebook":"https://www.facebook.com/Les-amis-de-la-CASA-144243456174379/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":43.9300981, 
      "longitude":2.1457825  
   },
   
   {
      "nom": "La coop sur mer",
      "departement":"83",
      "ville":"Toulon",
      "adresse":"Rue du Noyer",
      "logo":"coop_sur_mer.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://lacoopsurmer.fr/",
      "courriel":"",
      "facebook":"https://www.facebook.com/LaCoopSurMer/",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":43.1221575, 
      "longitude":5.9313922 
   },

   {
      "nom": "La cerise sur le Gapeau",
      "departement":"83",
      "ville":"La vallée du Gapeau",
      "adresse":"Placette du Moulin de la Capelle - Rue du Partégal - 83210 La Farlède",
      "logo":"cerise_gapeau.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://www.cooplacerise.fr/",
      "courriel":"contact@cooplacerise.fr",
      "facebook":"https://www.facebook.com/lacerisesurlegapeau/",     
      "statuts":"",
      "avancement":3,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":43.1660118, 
      "longitude":6.0380293  
   },

   {
      "nom": "Gem la coop",
      "departement":"84",
      "ville":"Avignon",
      "adresse":"",
      "logo":"gemlacoop.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://www.facebook.com/lesamiesgemlacoop/",
      "courriel":"contact@gem-la-coop.org",
      "facebook":"http://gem-la-coop.org/",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude": 43.943474, 
      "longitude":4.8073637
   },
   
   {
      "nom": "Lalouet coop",
      "departement":"85",
      "ville":"Les Herbiers",
      "adresse":"",
      "logo":"lalouette.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://www.lalouetcoop.fr/",
      "courriel":"",
      "facebook":"https://www.facebook.com/LalouetCoop/",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude": 46.8700321, 
      "longitude":-1.0170411
   },
  
   {
      "nom": "Le baudet",
      "departement":"86",
      "ville":"Poitiers",
      "adresse":"",
      "logo":"le_baudet.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://lebaudet.fr/",
      "courriel":"ghislain.bourdilleau@gmail.com",
      "facebook":"https://www.facebook.com/LeBaudetduPoitou/",     
      "statuts":"",
      "avancement":2,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude": 46.5800341, 
      "longitude":0.3381391
   },
   
   {
      "nom": "L'Ep'autre",
      "departement":"91",
      "ville":"Juvisy-sur-Orge",
      "adresse":"",
      "logo":"epautre.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://epautre.fr/",
      "courriel":"contact@epautre.fr",
      "facebook":"https://www.facebook.com/Ep.autre",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.6917422, 
      "longitude":2.3546643  
   },
  
   {
      "nom": "La French Coop",
      "departement":"92",
      "ville":"Asnières-sur-Seine",
      "adresse":"",
      "logo":"french_coop.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://lafrenchcoop.fr/site/",
      "courriel":"lesamisdelafrenchcoop@gmail.com",
      "facebook":"https://www.facebook.com/lafrenchcoop/",     
      "statuts":"",
      "avancement":3,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.9128508, 
      "longitude":2.2892066  
   },
   
   {
      "nom": "La caravane",
      "departement":"93",
      "ville":"Montreuil",
      "adresse":"",
      "logo":"caravane.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://lacaravanecoop.fr/",
      "courriel":"contact@lacaravanecoop.fr",
      "facebook":"https://www.facebook.com/Lacaravanedemontreuil/",     
      "statuts":"",
      "avancement":3,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.8637447, 
      "longitude":2.4315409  
   },

   {
      "nom": "Coop'cot",
      "departement":"94",
      "ville":"Valle de Marne",
      "adresse":"",
      "logo":"coopcot.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://coopcot.fr/",
      "courriel":"contact@coopcot.fr",
      "facebook":"https://fr-fr.facebook.com/supermarchecooperatif94/",     
      "statuts":"",
      "avancement":3,
      "objectifs":"",
      "fonctionnement":"", 
      "lattitude":48.7647331, 
      "longitude":2.4116822  
   },  
 
   {
      "nom": "La Calebasse",
      "departement":"971",
      "ville":"Guadeloupe",
      "adresse":"",
      "logo":"la_calebasse.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"",
      "courriel":"lacalebasse.coop@gmail.com",
      "facebook":"https://www.facebook.com/lacalebasse971/",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":16.2350099,
      "longitude":-61.560867
   },
 
   {
      "nom": "",
      "departement":"988",
      "ville":"Nouvelle Calédonie",
      "adresse":"",
      "logo":"lacoopanous.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://www.facebook.com/coopanous/",
      "courriel":"",
      "facebook":"http://lacoopanous.nc/",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":-22.25401,
      "longitude":166.5024829
   },

   {
      "nom": "BEES Coop",
      "departement":"BE",
      "ville":"Bruxelles",
      "adresse":"19 rue van hove – 1030 Schaerbeek",
      "logo":"bees_coop.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://bees-coop.be/",
      "courriel":"contact@bees-coop.be",
      "facebook":"https://www.facebook.com/CooperativeBEES/",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":50.8568779,
      "longitude":4.3751303  
   },  
      
   {
      "nom": "WooCoop",
      "departement":"BE",
      "ville":"Waterloo",
      "adresse":"55 Rue Bruyère-Saint-Jean",
      "logo":"woocoop.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://www.woocoop.be/",
      "courriel":"info@woocoop.be",
      "facebook":"https://www.facebook.com/WooCoop/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":50.714699,
      "longitude":4.3798098 
   },
   
   {
      "nom": "Oufticoop",
      "departement":"BE",
      "ville":"Liège",
      "adresse":"",
      "logo":"outficoop.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://www.oufticoop.be/",
      "courriel":"contact@oufticoop.be",
      "facebook":"https://www.facebook.com/Oufticoop-2003796329891655",     
      "statuts":"",
      "avancement":2,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":50.6245561,
      "longitude":5.4590053  
   },

   {
      "nom": "Coopeco",
      "departement":"BE",
      "ville":"Charleroi",
      "adresse":"Rue de l'Abattoir 12",
      "logo":"coopeco.svg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://coopeco-supermarche.be/",
      "courriel":"info@coopeco-supermarche.be",
      "facebook":"https://www.facebook.com/coopecosupermarche/",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":50.4067666,
      "longitude":4.3988897  
   },
 
   {
      "nom": "Vervicoop",
      "departement":"BE",
      "ville":"Verviers",
      "adresse":"rue de Heusy 30",
      "logo":"vervicoop.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://vervicoop.be/",
      "courriel":"info@vervicoop.be",
      "facebook":"https://www.facebook.com/vervicoop/",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":50.592732,
      "longitude":5.8666644 
   },
  
   {
      "nom": "La fève",
      "departement":"CH",
      "ville":"Meyrin",
      "adresse":"Rue des Arpenteurs 6",
      "logo":"la_feve.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://spp-vergers.ch/",
      "courriel":"info@spp-vergers.ch",
      "facebook":"https://www.facebook.com/SupermarcheParticipatifPaysan/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":46.2306729,
      "longitude":6.0667564
   },
   
   {
      "nom": "Le Nid",
      "departement":"CH",
      "ville":"Genève",
      "adresse":"3 Sentier des saules",
      "logo":"lenid.png",  
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://lenid.ch/",
      "courriel":"info@lenid.ch",
      "facebook":"https://www.facebook.com/lenidgeneve/",     
      "statuts":"",
      "avancement":4,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":46.2024878,
      "longitude":6.1286345
   },
   
   {
      "nom": "The People's <br>Supermarket",
      "departement":"GB",
      "ville":"Londres",
      "adresse":"72-78 Lamb's Conduit Street",
      "logo":"thepeoplessupermarket.jpg",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://www.thepeoplessupermarket.org/",
      "courriel":"gemma@thepeoplessupermarket.org",
      "facebook":"https://www.facebook.com/thepeoplessupermarket/",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":51.5226852,
      "longitude":-0.1190354
   },
   
   {
      "nom": "AlterCoop",
      "departement":"LU",
      "ville":"Luxembourg",
      "adresse":"",
      "logo":"altercoop.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"http://transitionstad.lu/project/altercoop-lux/",
      "courriel":"",
      "facebook":"https://www.facebook.com/AlterCoopLuxembourg/",     
      "statuts":"",
      "avancement":1,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":49.6115465,
      "longitude":6.1310611
   },
   
   {
      "nom": "Camilla",
      "departement":"IT",
      "ville":"Bologne",
      "adresse":"via Vincenzo Casciarolo 8",
      "logo":"camilla.png",
      "date_creation":"",
      "nb_membres":"",
      "contribution":"",
      "marge":"",
      "chiffre_affaire":"",
      "site_web":"https://camilla.coop/",
      "courriel":"info@camilla.coop",
      "facebook":"https://www.facebook.com/cooperativacamilla/",     
      "statuts":"",
      "avancement":5,
      "objectifs":"",
      "fonctionnement":"",
      "lattitude":44.5056731,
      "longitude":11.3602313
   },  
   
   ];
